apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: metal-load-balancer-controller-manager-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: metal-load-balancer-controller-manager
    app.kubernetes.io/instance: metal-load-balancer-controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: metal-load-balancer-controller-manager-leader-election-role
subjects:
  - kind: ServiceAccount
    name: metal-load-balancer-controller-manager
    namespace: {{ .Release.Namespace }}
