apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: metal-load-balancer-controller-manager-leader-election-role
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: metal-load-balancer-controller-manager
    app.kubernetes.io/instance: metal-load-balancer-controller-manager
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
