apiVersion: v1
kind: ServiceAccount
metadata:
  name: metal-load-balancer-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: metal-load-balancer-controller-manager
    app.kubernetes.io/instance: metal-load-balancer-controller-manager
    app.kubernetes.io/component: controller
