apiVersion: v1
kind: ConfigMap
metadata:
  name: metallb-excludel2
  namespace: "metal-operator-system"
  labels:
    helm.sh/chart: metallb-0.14.8
    app.kubernetes.io/name: metallb
    app.kubernetes.io/instance: metallb
    app.kubernetes.io/version: "v0.14.8"
    app.kubernetes.io/managed-by: Helm
data:
  excludel2.yaml: |
    announcedInterfacesToExclude:
      - ^docker.*
      - ^cbr.*
      - ^dummy.*
      - ^virbr.*
      - ^lxcbr.*
      - ^veth.*
      - ^lo$
      - ^cali.*
      - ^tunl.*
      - ^flannel.*
      - ^kube-ipvs.*
      - ^cni.*
      - ^nodelocaldns.*
