apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: metallb-controller
  namespace: "metal-operator-system"
  labels:
    helm.sh/chart: metallb-0.14.8
    app.kubernetes.io/name: metallb
    app.kubernetes.io/instance: metallb
    app.kubernetes.io/version: "v0.14.8"
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["metallb-memberlist"]
    verbs: ["list"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    resourceNames: ["metallb-controller"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["metallb.io"]
    resources: ["ipaddresspools"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metallb.io"]
    resources: ["bgppeers"]
    verbs: ["get", "list"]
  - apiGroups: ["metallb.io"]
    resources: ["bgpadvertisements"]
    verbs: ["get", "list"]
  - apiGroups: ["metallb.io"]
    resources: ["l2advertisements"]
    verbs: ["get", "list"]
  - apiGroups: ["metallb.io"]
    resources: ["communities"]
    verbs: ["get", "list","watch"]
  - apiGroups: ["metallb.io"]
    resources: ["bfdprofiles"]
    verbs: ["get", "list","watch"]
