//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by defaulter-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&WorkerConfig{}, func(obj interface{}) { SetObjectDefaults_WorkerConfig(obj.(*WorkerConfig)) })
	return nil
}

func SetObjectDefaults_WorkerConfig(in *WorkerConfig) {
	if in.ExtraIgnition != nil {
		if in.ExtraIgnition.SecretRef != nil {
			if in.ExtraIgnition.SecretRef.Name == "" {
				in.ExtraIgnition.SecretRef.Name = ""
			}
		}
	}
}
