apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metal-load-balancer-controller:speaker
  labels:
    app.kubernetes.io/name: metal-load-balancer-controller-speaker
    app.kubernetes.io/instance: metal-load-balancer-controller-speaker
subjects:
  - kind: ServiceAccount
    name: metal-load-balancer-controller-speaker
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metal-load-balancer-controller:speaker
