apiVersion: v1
kind: ServiceAccount
metadata:
  name: metal-load-balancer-controller-speaker
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: metal-load-balancer-controller-speaker
    app.kubernetes.io/instance: metal-load-balancer-controller-speaker
    app.kubernetes.io/component: speaker
